{
  pkgs,
  lib,
  inputs,
  ...
}: {
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    settings = {
      autogenerated = 0;

      # MONITORS
      monitor = ",preferred,auto,auto";

      # MY PROGRAMS
      "$terminal" = "kitty";
      "$fileManager" = "kitty -e yazi";
      "$menu" = "rofi -show drun";

      # AUTOSTART
      "exec-once" = [
        "fcitx5 -d"
        "noctalia-shell"
        "hyprctl setcursor catppuccin-mocha-lavender-cursors 24"
      ];

      windowrulev2 = [
        "float, class:^(linux-wallpaperengine)$"
        "pin, class:^(linux-wallpaperengine)$"
        "size 100% 100%, class:^(linux-wallpaperengine)$"
        "move 0 0, class:^(linux-wallpaperengine)$"
        "noborder, class:^(linux-wallpaperengine)$"
        "noshadow, class:^(linux-wallpaperengine)$"
        "noblur, class:^(linux-wallpaperengine)$"
        "noanim, class:^(linux-wallpaperengine)$"
        "nofocus, class:^(linux-wallpaperengine)$"
        "immediate, class:^(linux-wallpaperengine)$"
      ];

      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 3;
        "col.active_border" = lib.mkForce "rgba(f5bde6ee) rgba(c6a0f6ee) rgba(b7bdf8ee) 45deg";
        "col.inactive_border" = lib.mkForce "rgba(6e738daa)";
        resize_on_border = false;
        allow_tearing = false;
        layout = "dwindle";
      };

      decoration = {
        rounding = 20;
        active_opacity = 0.8;
        inactive_opacity = 0.6;
        
        shadow = {
          enabled = true;
          range = 15;
          render_power = 5;
          color = lib.mkForce "rgba(1a1a1aee)";
        };

        blur = {
          enabled = true;
          size = 13;
          passes = 1;
          vibrancy = 0.1696;
        };
      };

      animations = {
        enabled = "yes";

        bezier = [
          "crispBounce, 0.175, 0.885, 0.32, 1.275"
          "snappyPop, 0.34, 1.56, 0.64, 1.0"
          "sharpDrag, 0.25, 0.46, 0.45, 0.94"
          "quickEase, 0.4, 0, 0.2, 1"
        ];

        animation = [
          "windows, 1, 5, crispBounce"
          "windowsIn, 1, 6, snappyPop, popin 85%"
          "windowsOut, 1, 3, quickEase, popin 90%"
          "windowsMove, 1, 4, sharpDrag"
          "fadeIn, 1, 3, snappyPop"
          "fadeOut, 1, 2.5, quickEase"
          "fade, 1, 3, quickEase"
          "border, 1, 4, crispBounce"
          "layers, 1, 4, crispBounce"
          "layersIn, 1, 5, snappyPop"
          "workspaces, 1, 5, crispBounce"
          "workspacesIn, 1, 6, snappyPop"
          "workspacesOut, 1, 4, quickEase"
        ];
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      master = {
        new_on_top = true;
      };

      misc = {
        force_default_wallpaper = -3;
        disable_hyprland_logo = true;
        enable_swallow = true;
        swallow_regex = "^(kitty|Alacritty|wezterm)$";
      };

      cursor = {
        no_hardware_cursors = false;
        enable_hyprcursor = true;
      };

      # INPUT
      input = {
        kb_layout = "us";
        follow_mouse = 1;
        sensitivity = 0;
        touchpad.natural_scroll = false;
      };

      device = {
        name = "epic-mouse-v1";
        sensitivity = -0.5;
      };

      # KEYBINDINGS
      "$mainMod" = "SUPER";
      bind = [
        "$mainMod, Q, exec, $terminal"
        "$mainMod, C, killactive,"
        "$mainMod, M, exit,"
        "$mainMod, E, exec, $fileManager"
        "$mainMod, V, togglefloating,"
        "$mainMod, P, pseudo,"
        "$mainMod, J, togglesplit,"
        "$mainMod SHIFT, S, exec, hyprshot -m region --clipboard-only"
        ", Print, exec, hyprshot -m output --clipboard-only"
        "$mainMod, Print, exec, hyprshot -m region -o ~/Pictures/Screenshots"
        "$mainMod, R, exec, noctalia-shell ipc call launcher toggle"
        "$mainMod, left, movefocus, l"
        "$mainMod, right, movefocus, r"
        "$mainMod, up, movefocus, u"
        "$mainMod, down, movefocus, d"
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];
    };
  };
}
