{
  pkgs,
  lib,
  inputs,
  ...
}: let
  # 提取共用顏色變數，提升維護性
  colors = {
    active = "rgba(f5bde6ee) rgba(c6a0f6ee) rgba(b7bdf8ee) 45deg";
    inactive = "rgba(6e738daa)";
    shadow = "rgba(1a1a1aee)";
  };
in {
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    # 增加插件管理支援
    plugins = [
    ];

    settings = {
      autogenerated = 0;
      monitor = ",preferred,auto,auto";

      "$terminal" = "kitty";
      "$fileManager" = "kitty -e yazi";
      "$menu" = "rofi -show drun";

      "exec-once" = [
        "fcitx5 -d"
        "noctalia-shell"
        "hyprctl setcursor catppuccin-mocha-lavender-cursors 24"
      ];

      # 注意：請將外層的變數名稱從 windowrulev2 改為 windowrule
      windowrule = [
        "match:class ^(linux-wallpaperengine)$, float on"
        "match:class ^(linux-wallpaperengine)$, pin on"
        "match:class ^(linux-wallpaperengine)$, size 100% 100%"
        "match:class ^(linux-wallpaperengine)$, move 0 0"
        "match:class ^(linux-wallpaperengine)$, no_shadow on"
        "match:class ^(linux-wallpaperengine)$, no_blur on"
        "match:class ^(linux-wallpaperengine)$, no_anim on"
        "match:class ^(linux-wallpaperengine)$, no_focus on"
        "match:class ^(linux-wallpaperengine)$, immediate on"
      ];
      plugin = {
      };
      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 3;
        "col.active_border" = lib.mkForce colors.active;
        "col.inactive_border" = lib.mkForce colors.inactive;
        resize_on_border = false;
        allow_tearing = false;
        layout = "dwindle";
      };

      decoration = {
        rounding = 20;
        active_opacity = 0.8;
        inactive_opacity = 0.6;

        shadow = {
          enabled = true;
          range = 15;
          render_power = 5;
          color = lib.mkForce colors.shadow;
        };

        blur = {
          enabled = true;
          size = 13;
          passes = 1;
          vibrancy = 0.1696;
        };
      };

      animations = {
        enabled = "yes";
        bezier = [
          # ⚡ 極致清脆彈簧（大幅加速）
          "ultraSpring, 0.22, 0.32, 0.58, 1.3" # 超快彈簧 + 明顯超調
          "snapBounce, 0.15, 0.85, 0.35, 1.45" # 瞬間彈跳
          "quickSpring, 0.28, 0.18, 0.62, 1.1" # 快速回彈
          "sharpMove, 0.18, 0.52, 0.42, 0.98" # 銳利拖拽
          "microBounce, 0.12, 1.1, 0.25, 1.2" # 微調彈跳
        ];
        animation = [
          # 視窗進入：極速彈入 + 大超調
          "windowsIn, 1, 4, ultraSpring, popin 80%"
          # 視窗移動：超快拖拽反饋
          "windowsMove, 1, 6, sharpMove"
          # 視窗一般：snappy 微彈
          "windows, 1, 3, snapBounce"
          # 視窗退出：快速彈縮
          "windowsOut, 1, 3, quickSpring, slide 8% popin 85%"
          # 淡入淡出：極速
          "fadeIn, 1, 2, ultraSpring"
          "fadeOut, 1, 1.5, snapBounce"
          # UI：明顯彈簧反饋
          "border, 1, 4, microBounce"
          "layersIn, 1, 4, ultraSpring"
          "workspaces, 1, 3, snapBounce"
        ];
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      master = {
        new_status = "master";
      };

      misc = {
        force_default_wallpaper = -3;
        disable_hyprland_logo = true;
        enable_swallow = true;
        swallow_regex = "^(kitty|Alacritty|wezterm)$";
      };

      cursor = {
        # RTX 4060 在部分 0.54 環境下仍有硬體游標渲染異常的潛在風險，若遇到游標變黑可將此值改為 true
        no_hardware_cursors = false;
        enable_hyprcursor = true;
      };

      input = {
        kb_layout = "us";
        follow_mouse = 1;
        sensitivity = 0;
        touchpad.natural_scroll = false;
      };

      device = {
        name = "epic-mouse-v1";
        sensitivity = -0.5;
      };

      "$mainMod" = "SUPER";

      bind =
        [
          "$mainMod, Q, exec, $terminal"
          "$mainMod, C, killactive,"
          "$mainMod, M, exit,"
          "$mainMod, E, exec, $fileManager"
          "$mainMod, V, togglefloating,"
          "$mainMod, P, pseudo,"

          # 0.54 正式移除了 togglesplit 分屏調度器，必須改用 layoutmsg
          "$mainMod, J, layoutmsg, togglesplit"

          "$mainMod SHIFT, S, exec, hyprshot -m region --clipboard-only"
          ", Print, exec, hyprshot -m output --clipboard-only"
          "$mainMod, Print, exec, hyprshot -m region -o ~/Pictures/Screenshots"
          "$mainMod, R, exec, noctalia-shell ipc call launcher toggle"
          "$mainMod, left, movefocus, l"
          "$mainMod, right, movefocus, r"
          "$mainMod, up, movefocus, u"
          "$mainMod, down, movefocus, d"
        ]
        ++ (
          # 運用 Nix map 函數動態生成 1-9 的工作區切換與視窗移動綁定，大幅縮減配置行數
          map (i: "$mainMod, ${toString i}, workspace, ${toString i}") (lib.range 1 9)
        )
        ++ (
          map (i: "$mainMod SHIFT, ${toString i}, movetoworkspace, ${toString i}") (lib.range 1 9)
        )
        ++ [
          "$mainMod, 0, workspace, 10"
          "$mainMod SHIFT, 0, movetoworkspace, 10"
        ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];
    };
  };
}
