{
  pkgs,
  lib,
  ...
}: {
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    settings = {
      autogenerated = 0;

      # MONITORS
      monitor = ",preferred,auto,auto";

      # MY PROGRAMS
      "$terminal" = "kitty";
      "$fileManager" = "kitty -e yazi";
      "$menu" = "rofi -show drun";

      # AUTOSTART
      "exec-once" = [
        "fcitx5 -d"
        "noctalia-shell"
        "hyprctl setcursor catppuccin-mocha-lavender-cursors 24"
      ];

      windowrulev2 = [
        "float, class:^(linux-wallpaperengine)$"
        "pin, class:^(linux-wallpaperengine)$"
        "size 100% 100%, class:^(linux-wallpaperengine)$"
        "move 0 0, class:^(linux-wallpaperengine)$"
        "noborder, class:^(linux-wallpaperengine)$"
        "noshadow, class:^(linux-wallpaperengine)$"
        "noblur, class:^(linux-wallpaperengine)$"
        "noanim, class:^(linux-wallpaperengine)$"
        "nofocus, class:^(linux-wallpaperengine)$"
        "immediate, class:^(linux-wallpaperengine)$"
      ];

      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 3;
        "col.active_border" = lib.mkForce "rgba(f5bde6ee) rgba(c6a0f6ee) rgba(b7bdf8ee) 45deg";
        "col.inactive_border" = lib.mkForce "rgba(6e738daa)";
        resize_on_border = false;
        allow_tearing = false;
        layout = "dwindle";
      };

      decoration = {
        rounding = 20;
        active_opacity = 0.8;
        inactive_opacity = 0.6;
        shadow = {
          enabled = true;
          range = 15;
          render_power = 5;
          color = lib.mkForce "rgba(1a1a1aee)";
        };
        blur = {
          enabled = true;
          size = 13;
          passes = 1;
          vibrancy = 0.1696;
        };
      };

      animations = {
        enabled = "yes";

        bezier = [
          # ── 極致果凍主曲線 ── 強 overshoot + 多段回彈
          "jellyExtreme, 0.22, 1.05, 0.36, 1.55" # 超強回彈，落地會多抖
          "superBounce, 0.175, 0.885, 0.32, 1.95" # 彈跳兩三次，像果凍落地
          "dragJelly, 0.34, 1.56, 0.64, 1.35" # 拖動專用：明顯拉扯 + 晃動回彈
          "popExtreme, 0.05, 0.95, 0.10, 1.25" # popin 專用，極端彈出
          "easeOutQuint, 0.23, 1, 0.32, 1" # 保險平滑
        ];

        animation = [
          # 視窗出現：從超小 → 彈跳出來 + 多震 + 撞擊感
          "windows, 1, 7, jellyExtreme"
          "windowsIn, 1, 9, superBounce, popin 65%" # 65% 從極小彈出，超明顯多彈
          "windowsOut, 1, 4, linear, popin 80%"

          # 拖動 / 移動：最強果凍拉扯 + 晃動回彈（核心！）
          "windowsMove, 1, 7, dragJelly" # 拖動時拉長 → 猛彈回 → 小晃

          # 其他元素加強一致果凍感
          "fadeIn, 1, 4, popExtreme"
          "fadeOut, 1, 3.5, linear"
          "fade, 1, 4, easeOutQuint"
          "border, 1, 6, jellyExtreme"
          "layers, 1, 5, jellyExtreme"
          "layersIn, 1, 7, superBounce"
          "workspaces, 1, 7, jellyExtreme"
          "workspacesIn, 1, 8, superBounce"
          "workspacesOut, 1, 6, jellyExtreme"
        ];
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      master = {
        new_status = "master";
      };

      misc = {
        force_default_wallpaper = -3;
        disable_hyprland_logo = true;
        animate_mouse_windowdragging = true; # 滑鼠拖動時有動畫
        enable_swallow = true; # 加強拖動回饋
        swallow_regex = "^(kitty|Alacritty|wezterm)$";
      };

      # INPUT
      input = {
        kb_layout = "us";
        follow_mouse = 1;
        sensitivity = 0;
        touchpad.natural_scroll = false;
      };

      device = {
        name = "epic-mouse-v1";
        sensitivity = -0.5;
      };

      # KEYBINDINGS
      "$mainMod" = "SUPER";
      bind = [
        "$mainMod, Q, exec, $terminal"
        "$mainMod, C, killactive,"
        "$mainMod, M, exit,"
        "$mainMod, E, exec, $fileManager"
        "$mainMod, V, togglefloating,"
        "$mainMod, P, pseudo,"
        "$mainMod, J, togglesplit,"
        "$mainMod SHIFT, S, exec, hyprshot -m region --clipboard-only"
        ", Print, exec, hyprshot -m output --clipboard-only"
        "$mainMod, Print, exec, hyprshot -m region -o ~/Pictures/Screenshots"
        "$mainMod, R, exec, noctalia-shell ipc call launcher toggle"
        "$mainMod, left, movefocus, l"
        "$mainMod, right, movefocus, r"
        "$mainMod, up, movefocus, u"
        "$mainMod, down, movefocus, d"
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];
    };
  };
}
